services: 
    mongo:
        image: mongo
        env_file:
            - .env
        restart: always
    mongo-express:
        image: mongo-express
        env_file:
            - .env
        restart: always
        ports:
            - 8081:8081

    api:
        build:
            context: .
            dockerfile: api.Dockerfile
        env_file:
            - .env
        restart: always
        ports: 
            - 6543:6543
        depends_on:
            - mongo
        volumes:
            - ./data/img/upload:/data/img/upload
        # entrypoint: ["sh", "-c", "chown -R node:node /app/data/img/upload && node dist/main.js"]