server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy API calls to Express
    location /api {
        proxy_pass http://api:6543;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Serve gallery and upload images from shared volume
   location /img/ {
        proxy_pass http://api:6543;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /admin {
        auth_basic "Admin";
        auth_basic_user_file /etc/nginx/.htpasswd;

        add_header Set-Cookie "admin=true; Path=/";
        try_files /index.html =404;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}